### ISSUE TITLE
Write some code documentation

### ISSUE THREAD

**Issue by owanesh** [Owanesh/vaporwavely#2]
**🙇‍♂️ Idea of this project**

> Make vaporwave great again!

**✨ What i want to change with this issue?**
I hope to have a correct documentation.  

Enjoy! 🙌

**Comment by Meridien** [comment]
Hi there Owanesh. I have checked out your library and tested it in Windows CMD, Powershell, Idle, Putty, Raspbian terminal, and Termius. I found that there are various results in each:

- Windows Powershell & CMD: text looks the same as usual
- Putty (on Windows): strange looking characters
- Idle: looks good
- Raspbian: looks good
- Termius: looks good

I was thinking of submitting to you a PR with a section on which terminal programs get the best results, what do you think?

Thanks!

**Comment by owanesh** [comment]
It seems good! Feel free to open an PR 👍 
If you want write some code doc too (comments before function) i'll appreciate 😊
